server:
  port: 7002
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
      auto-index-creation: true
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080
spring.data.mongodb.host: mongodb
