server:
  port: 7001
  error:
    include-message: always


logging:
  level:
    root: INFO
    com.microservices: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server:
  port: 8080
